interface Language {
    name: string;
    variants: string[];
}

export const langauges = [
    { id: 1, name: "Alemán" },
    { id: 2, name: "Árabe" },
    { id: 3, name: "Búlgaro" },
    { id: 4, name: "Catalán" },
    { id: 5, name: "Checo" },
    { id: 6, name: "Chino" },
    { id: 7, name: "Croata" },
    { id: 8, name: "Danés" },
    { id: 9, name: "Eslovaco" },
    { id: 10, name: "Esloveno" },
    { id: 11, name: "Español" },
    { id: 12, name: "Estonio" },
    { id: 13, name: "Finlandés" },
    { id: 14, name: "Francés" },
    { id: 15, name: "Gallego" },
    { id: 16, name: "Griego" },
    { id: 17, name: "Húngaro" },
    { id: 18, name: "Holandés" },
    { id: 19, name: "Indonesio" },
    { id: 20, name: "Inglés" },
    { id: 21, name: "Italiano" },
    { id: 22, name: "Japonés" },
    { id: 23, name: "Letón" },
    { id: 24, name: "Lituano" },
    { id: 25, name: "Noruego" },
    { id: 26, name: "Polaco" },
    { id: 27, name: "Portugués" },
    { id: 28, name: "Ruso" },
    { id: 29, name: "Sueco" },
    { id: 30, name: "Turco" },
    { id: 31, name: "Ucraniano" },
];

export const languageIndex: { [key: number]: Language } = {
    1: { name: "Alemán", variants: ["Alemania", "Austria", "Suiza"] },
    2: {
        name: "Árabe",
        variants: ["Arabia Saudita", "Emiratos Árabes Unidos"],
    },
    3: { name: "Búlgaro", variants: ["Bulgaria"] },
    4: { name: "Catalán", variants: ["España", "Andorra"] },
    5: { name: "Checo", variants: ["República Checa"] },
    6: { name: "Chino", variants: ["China", "Taiwán"] },
    7: { name: "Croata", variants: ["Croacia"] },
    8: { name: "Danés", variants: ["Dinamarca"] },
    9: { name: "Eslovaco", variants: ["Eslovaquia"] },
    10: { name: "Esloveno", variants: ["Eslovenia"] },
    11: { name: "Español", variants: ["España", "México", "Argentina"] },
    12: { name: "Estonio", variants: ["Estonia"] },
    13: { name: "Finlandés", variants: ["Finlandia"] },
    14: { name: "Francés", variants: ["Francia", "Bélgica", "Suiza"] },
    15: { name: "Gallego", variants: ["España"] },
    16: { name: "Griego", variants: ["Grecia"] },
    17: { name: "Húngaro", variants: ["Hungría"] },
    18: { name: "Holandés", variants: ["Países Bajos", "Bélgica"] },
    19: { name: "Indonesio", variants: ["Indonesia"] },
    20: { name: "Inglés", variants: ["Estados Unidos", "Reino Unido"] },
    21: { name: "Italiano", variants: ["Italia", "Suiza"] },
    22: { name: "Japonés", variants: ["Japón"] },
    23: { name: "Letón", variants: ["Letonia"] },
    24: { name: "Lituano", variants: ["Lituania"] },
    25: { name: "Noruego", variants: ["Noruega"] },
    26: { name: "Polaco", variants: ["Polonia"] },
    27: { name: "Portugués", variants: ["Portugal", "Brasil"] },
    28: { name: "Ruso", variants: ["Rusia"] },
    29: { name: "Sueco", variants: ["Suecia"] },
    30: { name: "Turco", variants: ["Turquía"] },
    31: { name: "Ucraniano", variants: ["Ucrania"] },
};

export const speekingSpeeds = [
    "Muy lenta",
    "Lenta",
    "Normal",
    "Rápida",
    "Muy rápida",
];

export const egonIncludedOptions = [
    "SALUDOS Y DESPEDIDAS",
    "FECHA Y HORA",
    "NOTICIAS",
    "CLIMA",
    "RECORDATORIOS",
    "LISTAS",
    "MÚSICA",
    "TEMPORIZADORES Y ALARMAS",
    "BUSCADOR DE INTERNET",
    "VIDEOS Y PODCASTS",
];
