export const recipes = [
    {
        id: 1,
        type: "desayunos",
        name: "HUEVOS A LA MEXICANA",
        complete: false,
        toBuy: ["CEBOLLA"],
    },
    {
        id: 2,
        type: "desayunos",
        name: "PAN TOSTADO CON AGUACATE",
        complete: true,
        toBuy: [],
    },
    {
        id: 3,
        type: "desayunos",
        name: "PAN TOSTADO CON AGUACATE",
        complete: true,
        toBuy: [],
    },
    {
        id: 4,
        type: "desayunos",
        name: "HOT CAKES",
        complete: false,
        toBuy: ["MANTEQUILLA"],
    },
    {
        id: 5,
        type: "comidas",
        name: "TACOS DE CARNITAS",
        complete: false,
        toBuy: ["TORTILLAS", "CARNITAS"],
    },
    {
        id: 6,
        type: "comidas",
        name: "ENCHILADAS VERDES",
        complete: true,
        toBuy: [],
    },
    {
        id: 7,
        type: "comidas",
        name: "CHILES RELLENOS",
        complete: false,
        toBuy: ["CHILES POBLANOS", "QUESO"],
    },
    {
        id: 8,
        type: "comidas",
        name: "MOLE CON POLLO",
        complete: true,
        toBuy: [],
    },
    {
        id: 9,
        type: "cenas",
        name: "SÁNDWICH DE ATÚN",
        complete: false,
        toBuy: ["ATÚN", "PAN"],
    },
    {
        id: 10,
        type: "cenas",
        name: "QUESADILLAS CON POLLO",
        complete: true,
        toBuy: ["QUESO"],
    },
    {
        id: 11,
        type: "cenas",
        name: "ENSALADA CON POLLO",
        complete: true,
        toBuy: [],
    },
    {
        id: 12,
        type: "cenas",
        name: "POLLO CON VERDURAS",
        complete: true,
        toBuy: [],
    },
    {
        id: 13,
        type: "snacks",
        name: "ROLLITOS DE JAMÓN Y QUESO",
        complete: true,
        toBuy: [],
    },
    {
        id: 14,
        type: "snacks",
        name: "YOGURT CON FRUTAS",
        complete: true,
        toBuy: [],
    },
    {
        id: 15,
        type: "snacks",
        name: "SMOOTHIE DE PLATANO",
        complete: true,
        toBuy: [],
    },
    {
        id: 16,
        type: "snacks",
        name: "ZANAHORIA CON HUMMUS",
        complete: true,
        toBuy: [],
    },
];
