import eggs from "../../public/img/eggs.jpg";
import bread from "../../public/img/bread-salad.jpg";
import hotCakes from "../../public/img/hot-cakes.jpg";

export const recipes = [
    {
        id: 1,
        type: "desayunos",
        name: "HUEVOS A LA MEXICANA",
        description:
            "Huevos revueltos con jitomate, cebolla y chile, un clásico desayuno mexicano.",
        complete: false,
        toBuy: ["CEBOLLA"],
        image: eggs,
    },
    {
        id: 2,
        type: "desayunos",
        name: "PAN TOSTADO CON AGUACATE",
        description:
            "Pan tostado con aguacate fresco, ideal para un desayuno saludable.",
        complete: true,
        toBuy: [],
        image: bread,
    },
    {
        id: 4,
        type: "desayunos",
        name: "HOT CAKES",
        description: "Esponjosos hot cakes perfectos para un desayuno dulce.",
        complete: false,
        toBuy: ["MANTEQUILLA"],
        image: hotCakes,
    },
    {
        id: 5,
        type: "comidas",
        name: "TACOS DE CARNITAS",
        description: "Tacos tradicionales mexicanos con carnitas jugosas.",
        complete: false,
        toBuy: ["TORTILLAS", "CARNITAS"],
        image: bread,
    },
    {
        id: 8,
        type: "comidas",
        name: "MOLE CON POLLO",
        description: "Pollo bañado en mole, un platillo tradicional mexicano.",
        complete: true,
        toBuy: [],
        image: bread,
    },
    {
        id: 9,
        type: "cenas",
        name: "SÁNDWICH DE ATÚN",
        description: "Sándwich ligero y rápido con atún y vegetales.",
        complete: false,
        toBuy: ["ATÚN", "PAN"],
        image: bread,
    },
    {
        id: 10,
        type: "cenas",
        name: "QUESADILLAS CON POLLO",
        description:
            "Tortillas rellenas de queso y pollo, fáciles y deliciosas.",
        complete: true,
        toBuy: ["QUESO"],
        image: bread,
    },
    {
        id: 11,
        type: "cenas",
        name: "ENSALADA CON POLLO",
        description: "Ensalada fresca con pollo, ideal para una cena ligera.",
        complete: true,
        toBuy: [],
        image: bread,
    },
    {
        id: 12,
        type: "cenas",
        name: "POLLO CON VERDURAS",
        description: "Pollo cocido con una mezcla de verduras saludables.",
        complete: true,
        toBuy: [],
        image: bread,
    },
    {
        id: 13,
        type: "snacks",
        name: "ROLLITOS DE JAMÓN Y QUESO",
        description:
            "Rollitos sencillos de jamón y queso, perfectos para un snack rápido.",
        complete: true,
        toBuy: [],
        image: bread,
    },
    {
        id: 14,
        type: "snacks",
        name: "YOGURT CON FRUTAS",
        description: "Yogurt natural acompañado de frutas frescas.",
        complete: true,
        toBuy: [],
        image: bread,
    },
    {
        id: 15,
        type: "snacks",
        name: "SMOOTHIE DE PLATANO",
        description: "Bebida cremosa hecha con plátano y leche.",
        complete: true,
        toBuy: [],
        image: bread,
    },
    {
        id: 16,
        type: "snacks",
        name: "ZANAHORIA CON HUMMUS",
        description: "Bastones de zanahoria acompañados de hummus.",
        complete: true,
        toBuy: [],
        image: bread,
    },
];
