import type { Metadata } from "next";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import Page from "@/components/Page";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="grid grid-cols-12 h-screen py-10 overflow-y-scroll scrollbar-none">
                    <AppSidebar className="col-span-2 md:col-span-4 px-2 md:px-10 overflow-auto" />
                    <main className="col-span-10 md:col-span-8">
                        <Page>{children}</Page>
                    </main>
                </div>
            </body>
        </html>
    );
}
