import type { Metadata } from "next";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import Page from "@/components/Page";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="grid grid-cols-12 h-screen pb-10 pt-24 md:pt-16 overflow-y-scroll scrollbar-none">
                    <AppSidebar className="col-span-2 md:col-span-4 px-2 md:px-10 py-4 overflow-y-auto" />
                    <Page className="flex flex-col col-span-10 md:col-span-8 items-center justify-center px-10 h-full w-full py-4">
                        {children}
                    </Page>
                </div>
            </body>
        </html>
    );
}
